name: "Editor for ESPHome (Dev)"
description: "Dev version of ESPHome-Editor add-on!"
version: 0.1.0
url: https://github.com/Morcatko/EspHome-Editor
slug: "esphome_editor_dev"
panel_title: "Editor for ESPHome (Dev)"
panel_icon: mdi:storefront-edit-outline
init: false
hassio_api: true
hassio_role: manager
host_network: true
map:
  - type: addon_config
    read_only: false
    path: /app/work-folder/
ingress: true
ingress_port: 3000
image: morcatko/esphome-editor-dev
arch:
  - amd64
  - aarch64
  - armhf
  - armv7
