name: Editor for ESPHome
description: Streamline the creation and management of YAML configurations for
  ESPHome when handling multiple similar components or deploying numerous
  identical devices.
url: https://github.com/Morcatko/EspHome-Editor
slug: esphome_editor
image: morcatko/esphome-editor
version: 0.27.0
panel_title: Editor for ESPHome
panel_icon: mdi:storefront-edit-outline
init: false
ingress: true
ingress_port: 47829
hassio_api: true
host_network: true
environment:
  PORT: "47829"
map:
  - type: addon_config
    read_only: false
    path: /app/work-folder/
arch:
  - amd64
  - aarch64
