name: Editor for ESPHome
description: Streamline the creation and management of YAML configurations for
  ESPHome when handling multiple similar components or deploying numerous
  identical devices.
version: 0.10.0
url: https://github.com/Morcatko/EspHome-Editor
slug: esphome_editor
panel_title: Editor for ESPHome
panel_icon: mdi:storefront-edit-outline
init: false
hassio_api: true
hassio_role: manager
host_network: true
map:
  - type: addon_config
    read_only: false
    path: /app/work-folder/
ingress: true
ingress_port: 3000
image: morcatko/esphome-editor
arch:
  - amd64
  - aarch64
  - armhf
  - armv7
